language: node_js
os:
  - linux
node_js:
  - "node"
  - "4.2"
script:
  - "npm test"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start