language: node_js
sudo: true
os:
  - linux
node_js:
  - "node"
  - "4.2"
script:
  - "npm test"
env:
  - CXX=g++-4.8
  - NODE_ENV=test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
  code_climate:
    repo_token: 3c49134b164e7675bafe629c8b9b6791ef5df85a3af952ec0278bd522655c85a
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-4.8 -y
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_script:
  - cat './coverage/client-lcov.info' | codeclimate-test-reporter
