web:
  build: .
  links:
    - db
  ports:
    - "3000:3000"
db:
  image: rethinkdb
  ports:
    - "8080:8080"
  volumes_from:
    - dbData
dbData:
  image: busybox
  volumes:
    - /data
  command: echo Data Volume for db