web:
  build: .
  dockerfile: Dockerfile-dev
  volumes:
    - ".:/usr/src/app"
  links:
    - db
  ports:
    - "3000:3000"
webpack:
  build: .
  command: node_modules/.bin/webpack -w
  dockerfile: Dockerfile-dev
  volumes:
    - ".:/usr/src/app"
  environment:
    NODE_ENV: development
babel_server:
  build: .
  command: node_modules/.bin/babel --preset es2015-node5 --watch -d built/server server-src
  dockerfile: Dockerfile-dev
  volumes:
    - ".:/usr/src/app"
  environment:
    NODE_ENV: development
db:
  image: rethinkdb
  ports:
    - "8080:8080"
  volumes_from:
    - dbData
dbData:
  image: busybox
  volumes:
    - /data
  command: echo Data Volume for db